services:
  - type: web
    runtime: node
    name: cycle-admin-bot
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PUBLIC_BASE_URL
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TG_ADMIN_IDS
        sync: false
      - key: API_KEY
        generateValue: true
